name: Deploy package from master

on:
  push:
    branches:
      - master
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      # I use ${version:1} to remove first caracter from version, because it's a "v" and I don't want it 
      - name: Get greatest tag
        id: get_greatest_tag
        run: |
          git fetch --tags
          version=$(git tag | tail -1)
          echo "Greatest tag: $version"
          echo "::set-output name=version::${version:1}"
      
      - name: Read package json version
        id: read_package_json_version
        run: |
          content=`cat ./package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      
      - name: Compare versions
        id: compare_versions
        run: |
          packageJsonVersion=${{fromJson(steps.read_package_json_version.outputs.packageJson).version}}
          greatestTagVersion=${{steps.get_greatest_tag.outputs.version}}

          echo "Package Json Version: $packageJsonVersion"
          echo "Greatest Tag Version: $greatestTagVersion"
          
          packageJsonVersionSplittedByDot=(${packageJsonVersion//./ })
          greatestTagVersionSplittedByDot=(${greatestTagVersion//./ })

          if [ -n "$greatestTagVersion" ]; then
            if [ "${packageJsonVersionSplittedByDot[0]}" == "${greatestTagVersionSplittedByDot[0]}" ] && [ "${packageJsonVersionSplittedByDot[1]}" == "${greatestTagVersionSplittedByDot[1]}" ]; then
              echo "MAJOR AND MINOR ARE SAME"
            else
              echo "MAJOR AND MINOR ARE NOT SAME"
              exit 1
            fi
          fi
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: "${{fromJson(steps.read_package_json_version.outputs.packageJson).version}}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
  build:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      