name: test

on:
  push:
    branches:
      - release_v*

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Read branch name
        id: read_branch_name
        run: |
          branchName=${GITHUB_REF#refs/heads/}
          echo "Branch name: $branchName"
          echo "::set-output name=branchName::$branchName"

      